[package]
name = "bench_debug"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
func_wrap = "0.1.3"